# Seminar 1 - April 8, 2020

This is the interactive jupyter notebook created during the first seminar of data-mining-course

In [1]:
def take_square(x):
    """
    Returns the squared value of the argument x.
    """
    return x**x

In [2]:
take_square(2)

4

? can be used to get help on the functions, both core and custom created.

In [3]:
take_square?

Basic importing operation on modules.

In [4]:
from builtins import BaseException

Use semicolon to silence the output.

In [5]:
1+3

4

In [6]:
1+3;

**NumPy** for all the array manipulation 

In [7]:
import numpy as np

Variables are dynamicaly stored without assigning explicit types.

In [8]:
x = 2
y = "A string"
z = True

Standard multi element variable in python (mutable), is lists.

In [10]:
my_list = list(range(10))
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Indexing starts from 0 (Like all the sane programming languages, not like R)

In [13]:
my_list[0]

0

In [15]:
stringified_list = [str(i) for i in my_list]
stringified_list

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In python, different types can be stored in the same list.

In [18]:
mixed_list = [True, 3, "Yes", 0.71]
[type(item) for item in mixed_list]

[bool, int, str, float]

### Creating NumPy Arrays
Easier on the storage and computing since forces uniform elements in an array.

In [19]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

NumPy automatically converts data to be in the same format. In this case, it converts integers to floats.

In [20]:
np.array([0.5, 1, 2])

array([0.5, 1. , 2. ])

Nested lists create multi-dimensial data. 

In [21]:
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [22]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [23]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Create 3x3 array filled with 3.14

In [24]:
np.full((3, 3), 3.14)

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [28]:
# Create a sequence from 0 to 20, increasing by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
# Create 5 values evenly spaced from 0 to 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
# Create random numbers uniformly distributed between 0 and 1
np.random.random((3, 3))

array([[0.76059539, 0.30971346, 0.68718048],
       [0.45752662, 0.75633136, 0.26624745],
       [0.64511498, 0.55141327, 0.47053024]])

In [30]:
# Create random numbers with mean 0 and std of 1
np.random.normal(0, 1, (3, 3))

array([[ 0.82900605, -0.99950819,  1.89513623],
       [ 0.56681457, -0.15183753, -0.50143464],
       [-0.23154979,  1.6490875 ,  0.796314  ]])

In [32]:
np.random.randint(0, 10, (3, 3))

array([[5, 9, 1],
       [1, 3, 6],
       [9, 6, 9]])

In [33]:
# Create an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
# Determine a seed for random number generator, for reproducibility
np.random.seed(0)

NumPy array attributes and dimensions

In [35]:
x1 = np.random.randint(10, size=6)            # 1D Array
x2 = np.random.randint(10, size=(3, 4))       # 2D Array
x3 = np.random.randint(10, size=(3, 4, 5))    # 3D Array

In [36]:
x3.ndim, x3.shape, x3.size

(3, (3, 4, 5), 60)

In [41]:
x1

array([5, 0, 3, 3, 7, 9])

In [39]:
x1[0], x1[-1]

(5, 9)

In [42]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [40]:
x2[1,3], x2[-1, 0]

(8, 1)

In [45]:
x2[-1, 0] = 99
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [99,  6,  7,  7]])

**Slicing the arrays**

In [55]:
x1

array([5, 0, 3, 3, 7, 9])

In [46]:
x1[:5] # First 5 elements

array([5, 0, 3, 3, 7])

In [49]:
x1[5:] # Elemets after index 5 (5 included)

array([9])

In [53]:
x1[2:4] # Mid-slicing (Here it takes indexes 2 and 3, 4 not included)

array([3, 3])

In [54]:
x1[::2] # Step=2

array([5, 3, 7])

In [56]:
x1[::-1] # Reversed

array([9, 7, 3, 3, 0, 5])

In [57]:
x1[3::-2] # Reverse, with step=2 and starting from index=3

array([3, 0])

**Same in 2D arrays**

In [59]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [99,  6,  7,  7]])

In [58]:
x2[:2, :3] # First 2 rows, 3 columns

array([[3, 5, 2],
       [7, 6, 8]])

In [60]:
x2[:, ::2] # All rows, every other column

array([[ 3,  2],
       [ 7,  8],
       [99,  7]])

In [61]:
x2[:, 0] # First column of x2

array([ 3,  7, 99])

In [62]:
x2[0, :] # First row of x2

array([3, 5, 2, 4])

## Important Note
NumPy array slices are views, not copies. Mutating them mutates the parent array.

In [65]:
x2

array([[ 3,  5,  2,  4],
       [ 7,  6,  8,  8],
       [99,  6,  7,  7]])

In [64]:
x2_sub = x2[:2, :2]
x2_sub

array([[3, 5],
       [7, 6]])

In [67]:
x2_sub[0,0] = 0
x2

array([[ 0,  5,  2,  4],
       [ 7,  6,  8,  8],
       [99,  6,  7,  7]])

To copy, you call method .copy() on the array.

In [69]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[0, 5],
       [7, 6]])

In [70]:
x2_sub_copy[0,0] = 99
x2

array([[ 0,  5,  2,  4],
       [ 7,  6,  8,  8],
       [99,  6,  7,  7]])